"""Apply migrations

Revision ID: 60dd10cbeed8
Revises: fa9e01c9aa4b
Create Date: 2024-10-16 12:51:13.944056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60dd10cbeed8'
down_revision: Union[str, None] = 'fa9e01c9aa4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
